jobs:
  compile_pdf:
    name: Compile pdf
    runs-on: ubuntu-latest
    steps:
      - name: Install WKHTMLToPDF
        run: |
          mkdir wkhtmltopdf
          cd wkhtmltopdf
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb -O installer.deb
          sudo apt install ./installer.deb
          cd ..
      - name: Setup Node
        uses: actions/setup-node@v3.0.0
      - name: Display the path
        run: echo %PATH%
      - name: Make generator folder
        run: |
          mkdir generator
          cd generator
      - name: Clone Generator
        uses: actions/checkout@v1
        with:
          repository: tesis-lenguaje/generador-tesis
          path: generator
          ref: refs/heads/main
      - name: Install Dependencies
        run: cd ../generator && npm install
      - run: cd ..
      - uses: actions/checkout@v1
      - name: Configure generator
        run: >
          echo "export default { generador: '../generator/index.js' }" > config.mjs
      - name: Generando PDF
        run: node generar.mjs
      
      - run: ls build
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Uploading PDF
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./build/protocolo.pdf
          asset_name: protocolo.pdf
          asset_content_type: application/pdf

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:
